### ISSUE TITLE
[Bug]After 1.4 watusi get buggy

### ISSUE THREAD

**Issue by bathtimethiago** [opa334/TrollStore#359]
After update 1.4 I updated all my apps and now watusi doesn't work, I tried to uninstall it was difficult, the messages remained I don't know how, but when I ended up getting the app it is unavailable and disappears from the trollstore. When I install over it detects as non-trollstore installed and even installing tweak doesn't work

**Comment by opa334** [comment]
I'm debugging this with another user and this is definitely not related to TrollStore 1.4.

Besides that, all issues around weird behaviour should be fixed in 1.4.1. Reinstalling the IPA in that version should work.

**Comment by bathtimethiago** [comment]
I tried but keep not working

**Comment by opa334** [comment]
The issue where apps can sometimes not appear in TrollStore should be fixed in 1.4.2!

**Comment by bathtimethiago** [comment]
But when i uninstall WhatsApp the app data persist

**Comment by Sincelesssss** [comment]
Still the Same Problem After Update to 1.4.3 … Deinstallation and reinstall Watusi … WhatsApp Safe Settings , Watusi Not …

**Comment by bathtimethiago** [comment]
I installed normal WhatsApp and watusi on top and apparently it worked, I've already updated TS, I'll test it for a while to see if nothing happens

**Comment by Sincelesssss** [comment]
Onley watusi Over trollstore 1.4.3? And normal WhatsApp Form
App Store ? ... 

Which version of Watusi...

**Comment by bathtimethiago** [comment]
I uninstalled watusi from ts, installed normal WhatsApp from the AppStore and then installed watusi from ts and forced the installation

**Comment by Sincelesssss** [comment]
Where you get the Watusi ipa?

**Comment by bathtimethiago** [comment]
https://github.com/FouadRaheb/Watusi-for-WhatsApp

**Comment by Sincelesssss** [comment]
Yes i mean sideloading ipa or trollstore ipa ?

**Comment by Sincelesssss** [comment]
Get it ....

Okey have also made it...

Uninstall Watusi IPA for TrollStore in TrollStore.
Download WhatsApp from AppStore.
Install again the IPA from Watusi in TrollStore over it with "Force install".

Everything works again... whatever the error is.

**Comment by opa334** [comment]
Fixed in 1.4.4, if it's broken for you, you have to uninstall WhatsApp and reinstall in 1.4.4.

**Comment by zlRedness** [comment]
@Sincelesssss whats happened with the chats? Are the chat history still there with Watusi?
